language: python
arch:
  - amd64
  - ppc64le
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sudo apt-get install gnuplot-x11"
install:
  - pip install .
  - pip install numpy
  - pip install nose coverage
  # - pip install coveralls
  # - pip install pypiview
# command to run tests
script:
  - python example.py
  - python setup.py nosetests --cover-package pypiview  # --with-coverage

    #after_sucess:
    #coveralls
